#!/usr/bin/env node
/* Inline assets/pixel.js into the <head> of every page.
 *
 * WHY INLINE RATHER THAN <script src>. The club and Port to Port pages are
 * deliberately self-contained - every asset they reference is a same-directory
 * relative path - because each is served from TWO roots (seamanapp.com/club/
 * and seamanapp.com/course/port-to-port/, plus the canonical
 * course.seamanapp.com where the same file sits at "/"). Any ../assets/ path
 * would resolve on one host and 404 on the other, and a 404'd pixel fails
 * silently: the page still works, the tracking just never happens and nobody
 * finds out for a month. Inlining removes the question, and removes a request
 * from a page whose load weight was just cut 76%.
 *
 * Idempotent: re-running replaces the existing block rather than stacking.
 *
 *   node inject_pixel.mjs          # write
 *   node inject_pixel.mjs --check  # verify only, non-zero if any page is stale
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { globSync } from 'node:fs';

const CHECK = process.argv.includes('--check');
const OPEN = '<!-- meta-pixel:begin (generated by inject_pixel.mjs - edit assets/pixel.js, not this) -->';
const CLOSE = '<!-- meta-pixel:end -->';

const body = readFileSync('assets/pixel.js', 'utf8');
const block = `${OPEN}\n<script>\n${body.trim()}\n</script>\n${CLOSE}\n`;

const pages = globSync('**/index.html', { exclude: (p) => p.includes('node_modules') || p.includes('.git') });

let changed = 0, stale = [];
for (const file of pages.sort()) {
  const src = readFileSync(file, 'utf8');
  const existing = new RegExp(`${OPEN.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${CLOSE}\\n?`);

  let next;
  if (existing.test(src)) {
    next = src.replace(existing, block);
  } else if (src.includes('</head>')) {
    next = src.replace('</head>', `${block}</head>`);
  } else {
    console.log(`  SKIP  ${file} (no </head>)`);
    continue;
  }

  if (next === src) { console.log(`  ok    ${file}`); continue; }
  stale.push(file);
  if (!CHECK) { writeFileSync(file, next); changed++; console.log(`  wrote ${file}`); }
  else console.log(`  STALE ${file}`);
}

if (CHECK && stale.length) {
  console.error(`\n${stale.length} page(s) do not carry the current pixel. Run: node inject_pixel.mjs\n`);
  process.exit(1);
}
console.log(`\n${CHECK ? 'all pages current' : `${changed} page(s) updated`} (${pages.length} scanned)\n`);
